name: CI
on:
  push:
    branches:
    - master
jobs:
  release:
    name: Release SFSymbols
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Bundler
        run: bundle install
      - name: Create Release Tag
        run: bundle exec fastlane release
      - name: Push Release Tag
        run: |
          git commit -am "Automated report"
          git push
