name: Release
run-name: ${{ github.actor }} is creating a release.
on:
  push:
    branches:
    - master
jobs:
  release:
    name: Release SFSymbols
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      DANGER_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN }}
      DEVELOPER_DIR: /Applications/Xcode_15.3.app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependenies with Bundler
        run: bundle install
      - name: Unit Tests
        run: bundle exec fastlane unit_test
      - name: Create Release Tag
        run: bundle exec fastlane release_to_github
