name: Pull Request Against Master
run-name: ${{ github.actor }} is creating a change to `master`.
on:
  pull_request:
    branches:
    - master
jobs:
  tests:
    name: Unit Tests
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      DANGER_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN }}
      DEVELOPER_DIR: /Applications/Xcode_15.3.app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependenies with Bundler
        run: bundle install
      - name: Unit Tests
        run: bundle exec fastlane unit_test
