name: CI
on:
  pull_request:
    branches:
    - master
jobs:
  release:
    name: Release SFSymbols
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Bundler
        run: bundle install
      - name: Release SFSymbols
        run: bundle exec fastlane release
