name: CI
on:
  pull_request:
    branches:
    - develop
jobs:
  tests:
    name: Unit Tests
    runs-on: macOS-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Bundler
        run: bundle install
      - name: Unit Tests
        run: bundle exec fastlane unit_test
