name: Pull Request Against Develop
run-name: ${{ github.actor }} is creating a change.
on:
  pull_request:
    branches:
    - develop
jobs:
  tests:
    name: Unit Tests
    runs-on: macOS-13-xl
    env:
      DANGER_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
#      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Switch to Xcode Beta
        run: xcode-select -switch /Applications/Xcode_15.0.app
      - name: Install Dependenies with Bundler
        run: bundle install
      - name: Unit Tests
        run: bundle exec fastlane unit_test
